apiVersion: v1
kind: Service
metadata:
    name: simple-bank-api-service
spec:
    selector:
        app: simple-bank-api
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
    type: ClusterIP
