# compose_spec.json
version: "3.8"
services:
    simple_bank:
        image: postgres:15-alpine
        container_name: simple_bank
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD:user
            - POSTGRES_USER:postgres
